football_intelligence:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET_GOLD', 'football_gold') }}"
      threads: 4
      location: "{{ env_var('GCP_REGION', 'europe-west2') }}"
      priority: interactive
